<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WINDOWS-SBM5E6C" failures="0" tests="2" name="Uipath_Uibank_TestCases.LoginActions_TestCase" time="0.859" errors="1" timestamp="2022-06-01T20:11:37 IST" skipped="1">
  <testcase classname="Uipath_Uibank_TestCases.LoginActions_TestCase" name="loginActions_TestCase" time="0.000">
    <skipped/>
  </testcase> <!-- loginActions_TestCase -->
  <system-out/>
  <testcase classname="Uipath_Uibank_TestCases.LoginActions_TestCase" name="intiliaseFiles" time="0.859">
    <error message="class BatchNo30_Utility.Utility (in unnamed module @0x2d29b4ee) cannot access class jdk.internal.org.jline.utils.Log (in module jdk.internal.le) because module jdk.internal.le does not export jdk.internal.org.jline.utils to unnamed module @0x2d29b4ee" type="java.lang.IllegalAccessError">
      <![CDATA[java.lang.IllegalAccessError: class BatchNo30_Utility.Utility (in unnamed module @0x2d29b4ee) cannot access class jdk.internal.org.jline.utils.Log (in module jdk.internal.le) because module jdk.internal.le does not export jdk.internal.org.jline.utils to unnamed module @0x2d29b4ee
at BatchNo30_Utility.Utility.getDatetime(Utility.java:151)
at BatchNo30_Constants.Constant.<clinit>(Constant.java:17)
at BatchNo30_BaseClass.BaseClass.intiliaseFiles(BaseClass.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- intiliaseFiles -->
  <system-out/>
</testsuite> <!-- Uipath_Uibank_TestCases.LoginActions_TestCase -->
